services:
  gazebo:
    build: .
    container_name: ros2_gazebo

    ports:
      - "6080:6080"
      - "5900:5900"

    environment:
      - TURTLEBOT3_MODEL=burger
      - DISPLAY=:1
      - ROS_DOMAIN_ID=0

    volumes:
      - ./ros2_ws/packages:/ros2_ws/packages

    shm_size: "2gb"